
-- Look up index usage
SELECT   OBJECT_NAME(S.[OBJECT_ID]) AS [OBJECT NAME], I.[NAME] AS [INDEX NAME]
         , USER_SEEKS, USER_SCANS, USER_LOOKUPS, USER_UPDATES 
	FROM SYS.DM_DB_INDEX_USAGE_STATS AS S WITH (NOLOCK)
    INNER JOIN SYS.INDEXES AS I  WITH (NOLOCK)
		ON I.[OBJECT_ID] = S.[OBJECT_ID] 
        AND I.INDEX_ID = S.INDEX_ID 
	WHERE OBJECTPROPERTY(S.[OBJECT_ID],'IsUserTable') = 1 
		AND OBJECT_NAME(S.[OBJECT_ID]) = 'Mc_AhVal'								-- Table Name
		AND I.[NAME] = 'IDX_McAhVal_FieldTypCd_ActiveInd_EffFrom_EffThru'		-- Index Name
		AND (USER_SEEKS > 0 OR USER_SCANS > 0 OR USER_LOOKUPS > 0)				-- Was used